INSERT INTO FMS_MA_UPLOAD_CATEGORY(UC_ID,UC_NAME,UC_DESC) VALUES (NULL,'STUDENT','STUDENT DETAILS');
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE) VALUES (NULL,'PANCARD',1,'Pan Card Details',TRUE);
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE) VALUES (NULL,'TC',1,'Transfer certificate',TRUE);
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE) VALUES (NULL,'PHOTO',1,'Photo graph',TRUE);
INSERT INTO FMS_MA_CATEGORY_DOCTYPE(CD_ID,CD_TYPE,CD_UC_ID,CD_DESC,CD_MULTIPLE) VALUES (NULL,'MARKSHEET',1,'Photo graph',TRUE);


